version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB_NAME=Campaign_calculator
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_DB_USER=root
      - MYSQL_DB_NAME=Campaign_calculator
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: